
set(USER_COMPILE_SOURCES )

list(APPEND USER_COMPILE_SOURCES "${TCP_SERVER_ECHO_SRC}/main.c")

list(APPEND USER_COMPILE_SOURCES "${AC7020C_COMMON}/tasks/blink.c")
list(APPEND USER_COMPILE_SOURCES "${AC7020C_COMMON}/tasks/netinit.c")
list(APPEND USER_COMPILE_SOURCES "${AC7020C_COMMON}/tasks/tcpecho.c")
list(APPEND USER_COMPILE_SOURCES "${AC7020C_COMMON}/ac7020c/get_uid.c")

list(APPEND USER_INCLUDE_DIRECTORIES "${AC7020C_COMMON}/tasks")
list(APPEND USER_INCLUDE_DIRECTORIES "${AC7020C_COMMON}/ac7020c")
list(APPEND USER_INCLUDE_DIRECTORIES "${AC7020C_EXT_LIBS}")
