
set(USER_COMPILE_SOURCES )

list(APPEND USER_COMPILE_SOURCES "${TCP_SERVER_ECHO_SRC}/main.c")

list(APPEND USER_COMPILE_SOURCES "${AC7020C_COMMON_TASKS}/blink.c")
list(APPEND USER_COMPILE_SOURCES "${AC7020C_COMMON_TASKS}/netinit.c")

list(APPEND USER_INCLUDE_DIRECTORIES "${AC7020C_COMMON_TASKS}")
list(APPEND USER_INCLUDE_DIRECTORIES "${AC7020C_EXT_LIBS}")
