
set(USER_COMPILE_SOURCES )

set(USER_LINKER_SCRIPT "${BLINK_SRC}/lscript.ld")

list(APPEND USER_COMPILE_SOURCES "${BLINK_SRC}/main.c")

list(APPEND USER_COMPILE_SOURCES "${AC7020C_COMMON_TASKS}/blink.c")
list(APPEND USER_INCLUDE_DIRECTORIES "${AC7020C_COMMON_TASKS}")
